name: Master build

on:
  push:
    branches:
      - master
      - ABDM-Infra
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/helm/
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: |
          APP_VERSION=$(cat .appversion)
          echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
      - name: NCG Docker Registry
        env:
          DOCKER_REGISTRY_URL: docker.io
          NCG_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NCG_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $NCG_USERNAME -p $NCG_PASSWORD $DOCKER_REGISTRY_URL
      - name: Build docker image for NCG
        env:
          CONTAINER_REPO_NAME: hiu-ui
          NCG_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -f package/docker/Dockerfile -t $NCG_USERNAME/$CONTAINER_REPO_NAME:$ARTIFACT_VERSION .
      - name: Push Docker image to NCG Registry
        env:
          CONTAINER_REPO_NAME: hiu-ui
          NCG_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $NCG_USERNAME/$CONTAINER_REPO_NAME:$ARTIFACT_VERSION
      - name: Tag Docker Container with latest tag
        env:
          CONTAINER_REPO_NAME: hiu-ui
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker tag $DOCKER_USERNAME/$CONTAINER_REPO_NAME:$ARTIFACT_VERSION $DOCKER_USERNAME/$CONTAINER_REPO_NAME:latest
      - name: Push Latest Docker Container to Registry
        env:
          CONTAINER_REPO_NAME: hiu-ui
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $DOCKER_USERNAME/$CONTAINER_REPO_NAME:latest
      - name: Helm - Update Version and Image Tag
        run: |
          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Helm - Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: Bahmniindiadistro/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Helm - Copy chart
        run: mkdir -p helm-charts/hiu-ui/ && cp hiu-ui-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/hiu-ui/

      - name: Helm - reIndex
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://bahmniindiadistro.github.io/helm-charts/  .

      - name: Helm - Publish Chart
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of hiu-ui-${{ env.ARTIFACT_VERSION }}"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmniindiadistro/helm-charts.git' gh-pages


